# -*- mode: ruby -*-
# vi: set ft=ruby :

Dotenv.load

ENV['VAGRANT_DEFAULT_PROVIDER'] = "digital_ocean"

VAGRANTFILE_API_VERSION = "2"

$script = <<SCRIPT
cat<< EOF > /etc/sysconfig/iptables
*filter
:INPUT DROP [0:0]
:FORWARD DROP [0:0]
:OUTPUT ACCEPT [0:0]
-A INPUT -m state --state ESTABLISHED,RELATED -j ACCEPT
-A INPUT -p icmp -j ACCEPT
-A INPUT -i lo -j ACCEPT
-A INPUT -m state --state NEW -m tcp -p tcp --dport 22 -j ACCEPT
-A INPUT -m state --state NEW -m tcp -p tcp -s $1 -m multiport --dports 0:65535 -j ACCEPT
-A INPUT -m state --state NEW -m tcp -p tcp -s $2 -m multiport --dports 0:65535 -j ACCEPT
COMMIT
EOF
service iptables restart
SCRIPT

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.provider :digital_ocean do |provider, override|
    override.vm.hostname          = ENV['HOSTNAME']
    override.vm.box               = "digital_ocean"
    override.vm.box_url           = "https://github.com/smdahlen/vagrant-digitalocean/raw/master/box/digital_ocean.box"
    override.ssh.username         = ENV['SSH_USERNAME']
    override.ssh.private_key_path = ENV['SSH_KEY']

    provider.client_id            = ENV['CLIENT_ID']
    provider.api_key              = ENV['API_KEY']
    provider.ssh_key_name         = ENV['SSH_KEY_NAME']
    provider.region               = ENV['REGION']
    provider.image                = ENV['IMAGE']
    provider.size                 = ENV['MEMORY']
    provider.private_networking   = true
    provider.ca_path              = "/usr/local/share/ca-bundle.crt"
    provider.setup                = true

    # disable synced_folder: rsync is not installed on DigitalOcean's guest machine
    override.vm.synced_folder "./", "/vagrant", disabled: true

    # provision
    config.vm.provision "shell" do |s|
      s.inline = $script
      s.args = [ENV['PRIVATE_IP'], ENV['MY_GIP']]
    end
    config.vm.provision "shell", :path => '../script/install_mysql.sh'
  end
end
